server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productiondb?autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext